import { useState } from 'react'
import { BarChart3, Bell, BrainCircuit, CalendarDays, Home, Menu, Search, Settings, UserRound, X } from 'lucide-react'
import AuraMark from '../../../shared/components/AuraMark'

const items = [[Home, 'Dashboard'], [CalendarDays, 'Study Planner'], [BarChart3, 'Performance Analytics'], [BrainCircuit, 'AI Insights'], [BarChart3, 'Progress Report'], [Settings, 'Settings']]

export default function DashboardShell() {
  const [menuOpen, setMenuOpen] = useState(false)
  return <div className="min-h-dvh bg-[#f7f8fe] text-slate-900 lg:grid lg:grid-cols-[248px_1fr]">
    <aside className={`fixed inset-y-0 left-0 z-30 flex w-72 flex-col border-r border-slate-200 bg-white p-5 transition-transform lg:static lg:w-auto lg:translate-x-0 ${menuOpen ? 'translate-x-0' : '-translate-x-full'}`} aria-label="Main navigation"><div className="flex items-center justify-between"><div className="flex items-center gap-3 font-extrabold text-[#1749ca]"><AuraMark />Aura AI</div><button className="icon-button lg:hidden" onClick={() => setMenuOpen(false)} aria-label="Close navigation"><X /></button></div><p className="mt-1 text-xs text-slate-500">Academic Analytics</p><nav className="mt-8 space-y-1">{items.map(([Icon, label], index) => <button key={label} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-semibold focus-ring ${index === 0 ? 'bg-[#ddebff] text-[#1749ca]' : 'text-slate-600 hover:bg-slate-50'}`}><Icon className="size-4" />{label}</button>)}</nav><div className="mt-auto rounded-2xl bg-[#f1f5ff] p-4"><div className="flex items-center gap-2"><span className="grid size-9 place-items-center rounded-full bg-[#3566ff] text-sm font-bold text-white">A</span><div><p className="text-sm font-bold">Your profile</p><p className="text-xs text-slate-500">Plan settings</p></div></div></div></aside>
    {menuOpen && <button aria-label="Close navigation overlay" onClick={() => setMenuOpen(false)} className="fixed inset-0 z-20 bg-slate-950/30 lg:hidden" />}
    <div className="min-w-0"><header className="sticky top-0 z-10 flex h-16 items-center justify-between border-b border-slate-200 bg-white/90 px-4 backdrop-blur sm:px-7"><div className="flex items-center gap-3"><button className="icon-button lg:hidden" onClick={() => setMenuOpen(true)} aria-label="Open navigation"><Menu /></button><div><p className="text-sm font-extrabold sm:text-lg">Good morning</p><p className="hidden text-xs text-slate-500 sm:block">Your personalised study overview</p></div></div><div className="flex items-center gap-2"><label className="hidden items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm text-slate-400 md:flex"><Search className="size-4" /><input className="w-36 border-0 p-0 text-sm outline-none" placeholder="Search analytics…" /></label><button className="icon-button" aria-label="Notifications"><Bell /></button><button className="icon-button" aria-label="Profile"><UserRound /></button></div></header>
      <main className="grid min-h-[calc(100dvh-4rem)] place-items-center p-5 sm:p-8"><section className="w-full max-w-2xl rounded-3xl border border-dashed border-[#b8cdfb] bg-white p-7 text-center shadow-sm sm:p-12"><AuraMark className="mx-auto size-14" /><h1 className="mt-5 text-2xl font-extrabold">Your dashboard is ready for data</h1><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-slate-600">This is the responsive navigation shell. Dashboard cards and study data will connect when you are ready to add the backend.</p></section></main>
    </div>
  </div>
}
